### ISSUE TITLE
Nodeschool Women Edition #2 24. Mar. 2018

### ISSUE THREAD

**Issue by olso** [nodeschool/bratislava#43]
https://www.facebook.com/events/342864742877057/

**Comment by Ivkaa** [comment]
prepare some rehearsal after first nodeschool

**Comment by Ivkaa** [comment]
Poll:
- group projects? 
  - ask girls what would they like to code, make groups that could collaborate on some projects they like
  - prepare some project examples - nomadlist.com, cowork.progressbar.sk, donate.progressbar.sk

Reheral material:

javascript.info

Nodeschool material:

https://github.com/facebook/create-react-app
1) Install NPM + Node
2) `mkdir` `cd` `ls` `pwd` ... - explain (Win/Mac)
3) https://reactjs.org/tutorial/tutorial.html


x) git explain???

**Comment by Ivkaa** [comment]
Are you dreaming about what is like to code? Join our workshop that is open to anyone! We would like to encourage especially women this time. 👩🏾‍💻👩🏻‍💻👩‍💻 

Registration here: https://rmbrk.typeform.com/to/fO5RJt

Please bring your 💻 (laptop) and creativity.

There will be 🍕🍕🍕 and 🍹 for all of you.

The event will be held at a different location this time, since Progressbar has moved to Dunajska 14.

We will have 2 groups this time:
1) Begginers with no Javascript knowledge - no knowledge about computers or programming required
       - we will teach you Javascript basics
2) Those who attended 1. Nodeschool or have basic Javascript knowledge
       - we will teach you how to create you first webpage, command line basics, how to install and run node.js

Schedule for the day (approximate): 
  9:00 - Intro
  11:30 - Lunch
  15:45 - Final thoughts
  16:00 - Official end + Networking
  17:15 - Dinner together :)

Join our Nodeschool Bratislava facebook group https://www.facebook.com/groups/nodeschoolBratislava/

Join our Meetup group for further email updates
https://www.meetup.com/en-AU/nodejsbratislava/events/248697149/

You can find more info about what is Nodeschool at https://nodeschool.io/bratislava/

You can support Progressbar hackerspace at https://donate.progressbar.sk

You can subscribe for coworking in Progressbar https://cowork.progressbar.sk

**Comment by Player1os** [comment]
# Refreshing and grouping

We'll have some newcomers and possibly veterans from the last course that aren't too confident and would like to go through the stuff they learned last time.

That means there's gonna be a secondary group, which we'll be mentoring on JS apart from the main group, that's going through React.

I suggest posting the following on the Facebook event ( the last part is a poll, ya know to engage 'em :) ):

---

In this NodeSchool you'll learn how to build a simple React App! We'll be building on stuff you learned in the previous NodeSchool, but don't worry, we're also ready to go through the necessary JavaScript basics, you may have missed! We're going to have a group for each and you're free to switch between both groups at any time.

If you know some JS but aren't sure where you'll fit, check out this course https://github.com/node-girls/beginners-javascript. If you can handle the challenges, you're ready for React. In case you're having trouble with the challenges now, leave your comment bellow and we'll happily help you out :-)

Let us know in the poll how you're feeling!
- I'm ready to build React Apps
- I'd first like a fast course on JavaScript basics

**Comment by olso** [comment]
We should drink wine/porto
